#!/usr/bin/env bash
# cript transfers file from client to server using scp command
# Script accepts 4 parameters including:
# * Path to file to be transfered
# * IP address of the server to transfer the file to
# * Username scp connects with
# * Path to SSH private key that scp uses
# File is transfered to home directory of the server
# Strict host key checking is disabled while using scp

if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit "$E_BADARGS"
fi

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~
