#!/usr/bin/env bash
# The script transfers a file from a client to a server
# Accepts 4 parameters: path of file to be transferred, IP of the destination
# server, username scp connects with, and path to the SSH private key scp uses
# Displays 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
# if less than 3 parameters passed
# scp transfers the file to the user home directory ~/
# Strict host key checking is disabled when using scp

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit "$E_BADARGS"
fi
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~
