#!/usr/bin/env bash
# This bash script installs and configures a nginx server
# The server listens on port 80
# The server returns a page containing the string 'Hello World' when...
# queried at the root
# The server redirect permanently when /redirect_me is queried

apt-get update
apt-get install nginx -y

mkdir -p /var/www/abnb_alx.com/html

echo "Hello World!" | tee /var/www/abnb_alx.com/html/index.html >/dev/null

sed -i "s/root \/var\/www\/html/root \/var\/www\/abnb_alx.com\/html/g" /etc/nginx/sites-available/default

sed -i "/listen 80 default_server/a \\\n\trewrite ^/redirect_me\$ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;" /etc/nginx/sites-available/default

service nginx restart
