#!/usr/bin/env bash
# Installing and configuring nginx web server
# Configuring nginx redirect directive 

sudo apt update -y
sudo apt install nginx -y
sudo service nginx start

# Creating an index.html file in the web root
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Create location directive to redirect 'redirect_me' to another page
sudo sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4$request_uri;\n\t}/g' /etc/nginx/sites-available/default

# Create a symbolic link of the new server block in the /etc/nginx/sites-enabled directory
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Reload nginx
sudo nginx -s reload
