#!/usr/bin/env bash
# Installing and configuring nginx web server
# Configuring nginx redirect directive 

sudo apt update -y
sudo apt install nginx -y
sudo service nginx start

# Creating an index.html file in the web root
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Create location directive to redirect 'redirect_me' to another page
sudo sed -i "/server_name/a\\\n\trewrite ^/redirect_me https://medium.com/@obaresandy/ permanent;" /etc/nginx/sites-enabled/default

# Reload nginx
sudo service nginx restart

