#!/usr/bin/env bash
# loops from 1 to 20 using while loop
# displays "4" and then "bad luck from China" for the 4th loop iteration
# displays "9" and then "bad luck from Japan" for the 9th loop iteration
# displays "17 and then "bad luck from Italy" for the 17th loop iteration

n=1

while ((n <= 20))
do
	case "$n" in
		4)
			echo $n
			echo "bad luck From China"
			;;
		8)
			echo $n
			echo "bad luck from Japan"
			;;
		17)
			echo $n
			echo "bad luck from Italy"
			;;
		*)
			echo $n
	esac
	((n++))
done
