#!/usr/bin/env bash
# gives information about the 'school' file
# prints 'school file exists' if file exists
# prints 'school file does not exists' if file does not exist
# prints 'school file is empty' if file is empty
# prints 'school file is not empty' if file is not empty
# prints 'school file is a regular file' if file is a regular file

data='school'
if [ -e "$data" ]
then
	echo "school file exists"
	if [ -s "$data" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$data" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
