#!/usr/bin/env bash
# Changes /etc/hosts file such that:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

facebook='8.8.8.8	facebook.com'
cp /etc/hosts ~/hosts.new
sed -i 's/^127...0.*$/127.0.0.2\tlocalhost/' ~/hosts.new
echo "$facebook" >> ~/hosts.new
cp ~/hosts.new /etc/hosts
