#!/usr/bin/env bash
# A Bash script that creates an RSA key pair.
# Name of created private key is 'school'.
# Number of bits in the created key are 4096
# Created key is protected by passphrase 'betty'
ssh-keygen -f school -b 4096 -N betty
